# 1.Print 'Hello HCIA'.

In [1]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [3]:
a=2
b=8
print(a+b)

10


# 3.Define a list and replicate in three different ways.

In [4]:
a = ['1', '2', '3', '4',]
print([a]*4)
for i in range(4):
    print(a)
from itertools import repeat
list(repeat(a,4))

[['1', '2', '3', '4'], ['1', '2', '3', '4'], ['1', '2', '3', '4'], ['1', '2', '3', '4']]
['1', '2', '3', '4']
['1', '2', '3', '4']
['1', '2', '3', '4']
['1', '2', '3', '4']


[['1', '2', '3', '4'],
 ['1', '2', '3', '4'],
 ['1', '2', '3', '4'],
 ['1', '2', '3', '4']]

# 4.Define two lists and merge them together.

In [5]:
a = [1, 2]
b = [3, 4]
c = a + b
print (c)

[1, 2, 3, 4]


# 5. Get the last element of the list and print it.

In [6]:
a = [1, 2, 3, 4, 5]
print(a[4])

5


# 6.Define a tuple that contains only one element.

In [7]:
a = (8)
print(a)

8


# 7.Define a three-line long string.

In [8]:
a = '1\n2\n3'
print(a)


1
2
3


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [9]:
s=('s','o','s')
for i in range(3):
    print(s[i])

s
o
s


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [10]:
from operator import mul
mul(8,6)

48

# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [11]:
import numpy as np
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [12]:
import numpy as np
np.zeros((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [14]:
import numpy as np
a=np.arange(15,)
print(a)
a=np.arange(3,5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[3 4]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [15]:
import numpy as np
a = np.array([ [2, 1, 3], [2, 2, 4] ])
b = np.array([ [1, 1], [3, 2], [2, 4] ])
total = a.dot(b)
print(total)


[[11 16]
 [16 22]]
